spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost/api_banco
        username: root
        password: root
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: none
    main:
     allow-bean-definition-overriding: true
# --- server
server:
  port: 8081

logging:
  level:
    ROOT: DEBUG


   
